In [1]:
import numpy as np

In [3]:
x= np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
r=np.arange(0,9)
r.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
n=[1,2,0,0,4,0]
np.nonzero(n)

(array([0, 1, 4], dtype=int64),)

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.random((3,3,3))

array([[[0.7269168 , 0.2666285 , 0.46372536],
        [0.8963736 , 0.28090499, 0.31241406],
        [0.50305064, 0.25494382, 0.36321786]],

       [[0.6379615 , 0.47683753, 0.35777226],
        [0.94057923, 0.19630332, 0.08756512],
        [0.3118475 , 0.37198558, 0.55077032]],

       [[0.60631747, 0.64691098, 0.62463537],
        [0.47523299, 0.46456447, 0.61686131],
        [0.20360073, 0.17811309, 0.12947104]]])

In [34]:
v=np.random.random((10,10))
print(v)
print('')
print(v.min(),v.max())

[[0.2463378  0.05761259 0.17820403 0.92158507 0.37863145 0.99294005
  0.56532773 0.86261834 0.10728648 0.53594663]
 [0.32167502 0.05258526 0.92707284 0.49737158 0.73648842 0.71469468
  0.70458657 0.69044488 0.00676202 0.07748214]
 [0.90812761 0.43556073 0.67809104 0.22552891 0.93029351 0.64538486
  0.53419629 0.90849392 0.92909787 0.57691126]
 [0.68876617 0.56264723 0.06046755 0.6584955  0.42011282 0.81813805
  0.68260814 0.52848753 0.76237386 0.16433222]
 [0.09598915 0.48279162 0.46210528 0.59233892 0.41827743 0.35359007
  0.83631517 0.11039371 0.68051519 0.52401718]
 [0.22269465 0.04424744 0.62584542 0.76692989 0.76136793 0.00578816
  0.63710736 0.90481421 0.01368638 0.54442551]
 [0.78669305 0.00271489 0.70368792 0.87279606 0.20274881 0.80353541
  0.52862772 0.75891823 0.90131367 0.60700662]
 [0.61786306 0.61205294 0.38488755 0.91663194 0.07139309 0.3648643
  0.37677444 0.85669097 0.90224503 0.82054716]
 [0.8530055  0.94541209 0.46854683 0.72383161 0.58980918 0.23357723
  0.30700742 

In [40]:
v2=np.random.random((1,10))
print(v2)
print(v2.mean())
print()

[[0.17286573 0.74250199 0.61407664 0.97097311 0.6003763  0.72447679
  0.07924194 0.53214519 0.58344198 0.02163941]]
0.5041739076250346


In [43]:
np.diag([0,1, 2, 3, 4])

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [44]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmean, xstd = x.mean(), x.std()
x = (x - xmean)/xstd
print("After normalization:")
print(x)

Original Array:
[[0.34563339 0.35787399 0.23199009 0.66470742 0.2481554 ]
 [0.55309547 0.09446737 0.26787487 0.21510527 0.32697418]
 [0.33029543 0.48709011 0.24083312 0.00637979 0.62279952]
 [0.41799696 0.58522303 0.99865277 0.11652707 0.3279904 ]
 [0.35895403 0.14704535 0.4763117  0.67942031 0.38790852]]
After normalization:
[[-0.15755398 -0.10072954 -0.68511942  1.32368095 -0.61007531]
 [ 0.80554566 -1.32354009 -0.51853178 -0.7635037  -0.24417547]
 [-0.22875726  0.49912947 -0.64406747 -1.73246838  1.12913222]
 [ 0.17837885  0.95469119  2.87395292 -1.2211325  -0.23945792]
 [-0.09571566 -1.07945774  0.44909292  1.39198252  0.03869952]]


In [45]:
v3=[1,2,3,4,5]
v4=[0,1,4,6,7]
np.intersect1d(v3,v4)

array([1, 4])

In [52]:
v4= np.random.random((10))
print(v4)
v4.sort()
print(v4)

[0.61511601 0.17209945 0.42701661 0.19272728 0.51688994 0.79154264
 0.36777509 0.61986248 0.14032007 0.13406273]
[0.13406273 0.14032007 0.17209945 0.19272728 0.36777509 0.42701661
 0.51688994 0.61511601 0.61986248 0.79154264]


In [60]:
v5=np.random.random((10))
print(v5)
v5[np.argmax(v5)]=0
print(v5)


[0.43583845 0.19749375 0.96863399 0.43779844 0.76705591 0.15966035
 0.00615239 0.07779783 0.24594405 0.19390488]
[0.43583845 0.19749375 0.         0.43779844 0.76705591 0.15966035
 0.00615239 0.07779783 0.24594405 0.19390488]


In [74]:
v6=np.random.random((3,3))
print(v6)
v7 = v6 - v6.mean(axis=1, keepdims=True)
print(v7)

[[0.15323573 0.34368566 0.84221713]
 [0.21127141 0.84167072 0.33707856]
 [0.25569645 0.60485744 0.80347594]]
[[-0.29314377 -0.10269385  0.39583762]
 [-0.25206882  0.37833049 -0.12626167]
 [-0.29898016  0.05018083  0.24879933]]


In [83]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
sorted_index_array = np.argsort(Z)
# sorted array
sorted_array = Z[sorted_index_array]
rslt = sorted_array[-n : ]
print(rslt)

[9995 9996 9997 9998 9999]


In [100]:
v8=np.random.randint(low=0,high=10,size=(5,3))
print(v8)
v9=np.where(v8 > 4, v8*v8 , v8)
print(v9)

[[4 5 0]
 [0 3 2]
 [5 4 5]
 [7 7 6]
 [2 5 1]]
[[ 4 25  0]
 [ 0  3  2]
 [25  4 25]
 [49 49 36]
 [ 2 25  1]]
